### ISSUE TITLE
Python doesn't have SSL support

### ISSUE THREAD

**Issue by boberfly** [johnhaddon/gafferDependencies#1]
Just a small request and not an issue with Gaffer per-se. If the Python that comes with gafferDependencies could be rebuilt using OpenSSL as httplib hasn't got HTTPS support out of the box, this would be great. On CentOS openssl-devel just needs to be available for Python to pick up its headers.

**Comment by johnhaddon** [comment]
Sorry, I don't know how I missed this until today. Funnily enough, today was also the day I built gafferDependencies on CentOS with openssl-devel installed. The resulting binaries made the Travis tests fail, because the built-with-openssl python was running on a without-ssl test box. I guess that means we'd have to package openssl with Gaffer as well. I'm rather put off doing that by the big warning about import/export licenses on their homepage though. Any thoughts?

**Comment by boberfly** [comment]
Up to you on that one, it's only a licensing issue with the Python binary release in gafferDependencies, right? For my tests I've just built Python locally on my CentOS machine with OpenSSL and continued onwards on top of the Gaffer binary release. Most likely I'll be building Cortex/Gaffer from scratch anyway.

**Comment by johnhaddon** [comment]
OK, since you're making your own builds anyway, I think I'll maintain the status quo in the standard Gaffer builds for now. Thanks...
