### ISSUE TITLE
Possibility for a develop branch with more up-to-date dependencies?

### ISSUE THREAD

**Issue by HughMacdonald** [johnhaddon/gafferDependencies#4]
Cool stuff.

Out of interest, what would you think of having some kind of "develop" branch to gafferDependencies which has more up-to-date (maybe even ahead of stable) versions of the dependencies. The one that cropped up recently was OIIO 1.6, which isn't stable yet, but include better error reporting, which may have helped @andrewkauffman with the CCITTRLE compression issue with writing Tiffs.

It would also allow for more testing of newer libraries before pulling them into the master dependencies...

**Comment by HughMacdonald** [comment]
It connection with this, is there a good place for discussion of what dependencies may be updated in the near future?

**Comment by johnhaddon** [comment]
I guess my main aims/priorities for the gafferDependencies repo are as follows :

- Get people up and running building gaffer as quickly as possible
- Steer people towards a recommended set of versions that are tested and known to work well together
- Provide a reference for how we build the dependencies
- Document any tweaks made to the sources
- Have a record of what dependencies were used to build each of the gaffer releases

I do have some concerns that a "develop" branch might detract a little from those aims - for instance, by confusing people as to which prebuilt packages they should use.

I've also found that one of my main motivations for using more bleeding edge dependencies is when I've been adding features or fixing bugs in OIIO or OSL, and there I need to be working from those repos directly rather than from within gafferDependencies. With that in mind, I have wondered if it would be beneficial to tweak the various build scripts so that they could be pointed at an alternative version of the sources, so you could use buildOIIO.sh from gafferDependencies to build the latest bleeding edge sources, but hosting those outside of the gafferDependencies repo itself. Would that sort of thing address some of your needs too?

As for where to discuss the updating of dependencies, I'd guess the gaffer-dev mailing list is probably the best place. My general feeling though is that we should converge on the VFX Reference Platform as our standard...

**Comment by HughMacdonald** [comment]
That all makes sense. Pushing towards VFX Platform is obviously definitely a good way to go.

I think what I need to do is get to the stage where I can easily build my own dependencies so that I can test with different versions just for my own benefit.

You may well have your own, but I just knocked up this in google docs for my own benefit - happy to share if you'd like. Obviously incomplete (I only put the items that were specifically included in gafferDependencies in)

![gaffer_dependencies](https://cloud.githubusercontent.com/assets/625512/11029730/d7ac4896-86c0-11e5-95e4-9de18afea25f.png)

**Comment by johnhaddon** [comment]
Thanks Hugh - that's really useful. I don't see any reason we can't bump up the EXR, OCIO, Boost and TBB dependencies to match VFX2016 right away. As I understand it the Qt/PySide versions aren't quite ready yet, and I think would require significant testing in any case, so I think we should move more cautiously on those.

**Comment by HughMacdonald** [comment]
I guess the gcc and glibc versions are only really applicable for the pre-build dependencies and Gaffer. Bringing the ones you mentioned up would mean that it should be possible to get Gaffer VFX Ref Platform CY2015 compliant, which would then give a launching platform for getting it up to CY2016.

I'll share the Google Doc with you

**Comment by HughMacdonald** [comment]
One thing with this - if you want to get it compliant with VFX2015, if you are wanting to bring the OpenVDB stuff in, that would need down-grading to 3.0.x, from the 3.1.0 that's in the branch.

**Comment by johnhaddon** [comment]
The VDB branch isn't something that's gonna be merged any time soon - I just started mucking about at home with it, and really haven't got anywhere with it yet. Still, it'd be very cool I think - I reckon it'd slot into Gaffer's node-based scene processing really quite well.

**Comment by johnhaddon** [comment]
Closing this, since I think managing a single set of supported dependencies is more than enough effort. Anyone is of course free to fork and manage a develop branch of their own, and make pull requests from it at any time...
